version: "3.8"

services:
  # server service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: aia-server
    container_name: aia-server
    ports:
      - "8085:80" # Connect localhost 80 port to container 80 port
    networks:
      - app-network
    volumes:
      - ./server/nginx/:/etc/nginx/
  # api service
  api:
    build:
      context: ./api
      target: ${BUILD_TARGET}
      dockerfile: Dockerfile
    image: azharalifauzi/aia-api
    container_name: aia-api
    volumes:
      - ./api/:/app
      - /app/node_modules
      - /app/dist
    ports:
      - "5000:5000"
    networks:
      - app-network
    environment:
      - FLICKR_API_KEY=${FLICKR_API_KEY}
  # client service
  client:
    build:
      context: ./client
      target: ${BUILD_TARGET}
      dockerfile: Dockerfile
    image: azharalifauzi/aia-client
    container_name: aia-client
    volumes:
      - type: bind
        source: ./client/
        target: /app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - CHOKIDAR_USEPOLLING=true

networks:
  app-network:
    driver: bridge

volumes:
  web-root:
    driver: local
